export default {
  TRUSTEDFORM: 'TRUSTEDFORM',
  LOADED: 'LOADED',
  INTERACTED: 'INTERACTED',
  FIELD_CHANGED: 'FIELD_CHANGED',
  STEP_CHANGED: 'STEP_CHANGED',
  STEP_COMPLETED: 'STEP_COMPLETED',
  SUBMIT: 'SUBMIT',
  SUBMIT_SUCCESS: 'SUBMIT_SUCCESS',
  SUBMIT_ERROR: 'SUBMIT_ERROR'
}
